## Intro

In [2]:
import numpy as np

**Create a simple array**

In [6]:
a1 = np.array([1,2,3]) #numpy array

*vs*

In [7]:
l1 = [1,2,3] #normal python list

-----

In [9]:
a2 = np.arange(100) #range in numpy

*vs*

In [10]:
l2 = range(100) #range in python

-------

**Basic array operation**

*Get the dimension of an array*

In [16]:
a3 = np.array([[1,2],[3,4],[5,6]])
a3.ndim

2

*Byte size of each element*

In [19]:
print("a3", a3.itemsize)
a4 = np.array([1,4])
print("a4", a4.itemsize)

8

----

*Change the default type*

In [26]:
a5 = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(a5.itemsize)
print(a5)
a5 = np.array([[1,2],[3,4],[5,6]], dtype=complex)
print(a5.itemsize)
print(a5)

8
[[1. 2.]
 [3. 4.]
 [5. 6.]]
16
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


*Size of array*

In [28]:
print(a5.size)
a6 = np.array([1,2])
print(a6.size)

6
2


*Shape of array*

In [29]:
a5.shape

(3, 2)

*Initialize arrays*

In [39]:
print(np.zeros((2,5)))
print(np.ones((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


*Reshape dimension*

In [40]:
a7 = np.array(([1,2],[3,4],[5,6]))
a7.shape

(3, 2)

In [41]:
a7.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a7.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [44]:
a7.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a7.ravel() #return the flatten the array 

array([1, 2, 3, 4, 5, 6])

*Basic operations*

In [46]:
print(a7.min())
print(a7.max())
print(a7.sum())

1
6
21


<img src="./axis.png" alt="Drawing" style="width: 200px;"/>

In [49]:
a7.sum(axis=0)

array([ 9, 12])

In [50]:
a7.sum(axis=1)

array([ 3,  7, 11])

In [51]:
np.sqrt(a7)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [53]:
np.std(a7) #standard deviation

1.707825127659933

*Basic math operation*

In [54]:
a8 = np.array([[9,8],[7,6],[5,4]])

In [55]:
a7+a8

array([[10, 10],
       [10, 10],
       [10, 10]])

In [57]:
a7*a8

array([[ 9, 16],
       [21, 24],
       [25, 24]])

In [58]:
a7/a8

array([[0.11111111, 0.25      ],
       [0.42857143, 0.66666667],
       [1.        , 1.5       ]])

In [63]:
a8 = a8.reshape(2,3)
a7.dot(a8)

array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]])

*Indexing and slicing*

In [66]:
a9 = np.array([5,4,5,6])
a9[0:3]

array([5, 4, 5])

In [70]:
a10 = np.array([[3,3,4],[4,2,5],[5,52,23]])
print(a10)
a10[1:3,2] #first arg is row and second is col so it goes to first row and prints the 2 indexed item and second row


[[ 3  3  4]
 [ 4  2  5]
 [ 5 52 23]]


array([ 5, 23])

In [71]:
a10[-1]

array([ 5, 52, 23])

In [72]:
a10[-1, 0:2]

array([ 5, 52])

In [73]:
a10[:,1:3]

array([[ 3,  4],
       [ 2,  5],
       [52, 23]])

*Flatten the array*

In [76]:
for cell in a10.flat:
    print(cell)

3
3
4
4
2
5
5
52
23


*Stack and split the array*

In [88]:
a11 = np.random.rand(3,3)
print('a11=', a11)
a12 = np.random.rand(3,3)
print('a12=', a12)
print('vertical stack:', np.vstack((a11,a12)))
print('horizontal stack:', np.hstack((a11,a12)))

a11= [[0.13079584 0.26880313 0.3406167 ]
 [0.40019251 0.07944542 0.98993564]
 [0.56601671 0.25020732 0.45810921]]
a12= [[0.97014733 0.25915561 0.07677802]
 [0.43028341 0.95955615 0.35018592]
 [0.66238689 0.63838023 0.69634298]]
vertical stack: [[0.13079584 0.26880313 0.3406167 ]
 [0.40019251 0.07944542 0.98993564]
 [0.56601671 0.25020732 0.45810921]
 [0.97014733 0.25915561 0.07677802]
 [0.43028341 0.95955615 0.35018592]
 [0.66238689 0.63838023 0.69634298]]
horizontal stack: [[0.13079584 0.26880313 0.3406167  0.97014733 0.25915561 0.07677802]
 [0.40019251 0.07944542 0.98993564 0.43028341 0.95955615 0.35018592]
 [0.56601671 0.25020732 0.45810921 0.66238689 0.63838023 0.69634298]]


In [97]:
a13 = np.random.rand(2,15)
print('a13=', a13)
print('------------')
print('hsplit:',np.hsplit(a13, 3))

a13= [[0.77163351 0.68781106 0.3878507  0.41073713 0.33903132 0.54254564
  0.1934058  0.6819048  0.71710763 0.73997968 0.17723561 0.2493671
  0.20639617 0.3558236  0.35205535]
 [0.02151244 0.71615991 0.30436228 0.06239616 0.73979364 0.7876514
  0.97066642 0.22617755 0.62824419 0.5202578  0.30248983 0.49254646
  0.07951832 0.66733219 0.52496156]]
------------
hsplit: [array([[0.77163351, 0.68781106, 0.3878507 , 0.41073713, 0.33903132],
       [0.02151244, 0.71615991, 0.30436228, 0.06239616, 0.73979364]]), array([[0.54254564, 0.1934058 , 0.6819048 , 0.71710763, 0.73997968],
       [0.7876514 , 0.97066642, 0.22617755, 0.62824419, 0.5202578 ]]), array([[0.17723561, 0.2493671 , 0.20639617, 0.3558236 , 0.35205535],
       [0.30248983, 0.49254646, 0.07951832, 0.66733219, 0.52496156]])]


In [98]:
print('vsplit:',np.vsplit(a13, 2))

vsplit: [array([[0.77163351, 0.68781106, 0.3878507 , 0.41073713, 0.33903132,
        0.54254564, 0.1934058 , 0.6819048 , 0.71710763, 0.73997968,
        0.17723561, 0.2493671 , 0.20639617, 0.3558236 , 0.35205535]]), array([[0.02151244, 0.71615991, 0.30436228, 0.06239616, 0.73979364,
        0.7876514 , 0.97066642, 0.22617755, 0.62824419, 0.5202578 ,
        0.30248983, 0.49254646, 0.07951832, 0.66733219, 0.52496156]])]


*Boolean operation*

In [99]:
b = a13 > 0.3
b

array([[ True,  True,  True,  True,  True,  True, False,  True,  True,
         True, False, False, False,  True,  True],
       [False,  True,  True, False,  True,  True,  True, False,  True,
         True,  True,  True, False,  True,  True]])

In [101]:
a13[b] #only return values that has True boolean in b

array([0.77163351, 0.68781106, 0.3878507 , 0.41073713, 0.33903132,
       0.54254564, 0.6819048 , 0.71710763, 0.73997968, 0.3558236 ,
       0.35205535, 0.71615991, 0.30436228, 0.73979364, 0.7876514 ,
       0.97066642, 0.62824419, 0.5202578 , 0.30248983, 0.49254646,
       0.66733219, 0.52496156])

In [103]:
a13[b]=-1 #replace False as -1
print(a13)

[[-1.         -1.         -1.         -1.         -1.         -1.
   0.1934058  -1.         -1.         -1.          0.17723561  0.2493671
   0.20639617 -1.         -1.        ]
 [ 0.02151244 -1.         -1.          0.06239616 -1.         -1.
  -1.          0.22617755 -1.         -1.         -1.         -1.
   0.07951832 -1.         -1.        ]]


**Iteration in array**

In [105]:
for x in a13.flatten():
    print(x)

-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.1934058046899798
-1.0
-1.0
-1.0
0.17723560828555074
0.24936710496561976
0.20639616896888857
-1.0
-1.0
0.021512441614586653
-1.0
-1.0
0.06239615858776715
-1.0
-1.0
-1.0
0.22617755225519365
-1.0
-1.0
-1.0
-1.0
0.07951832171235107
-1.0
-1.0


In [107]:
for x in np.nditer(a13,order='C'): #same as above
    print(x)

-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.1934058046899798
-1.0
-1.0
-1.0
0.17723560828555074
0.24936710496561976
0.20639616896888857
-1.0
-1.0
0.021512441614586653
-1.0
-1.0
0.06239615858776715
-1.0
-1.0
-1.0
0.22617755225519365
-1.0
-1.0
-1.0
-1.0
0.07951832171235107
-1.0
-1.0


In [109]:
for x in np.nditer(a13,order='F'): #fortan order
    print(x)

-1.0
0.021512441614586653
-1.0
-1.0
-1.0
-1.0
-1.0
0.06239615858776715
-1.0
-1.0
-1.0
-1.0
0.1934058046899798
-1.0
-1.0
0.22617755225519365
-1.0
-1.0
-1.0
-1.0
0.17723560828555074
-1.0
0.24936710496561976
-1.0
0.20639616896888857
0.07951832171235107
-1.0
-1.0
-1.0
-1.0


<img src="./nditer-order.png" width="200" height="200"/>

In [115]:
In[109]

"for x in np.nditer(a13,order='F'): #fortan order\n    print(x)"